# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ccd912e8c2ffe37a1f533a4403d1ba994637758335e837037786001a2ff6cb6f2da174e03ddcf29593c2eedcb0de0fbaf9faf0295da13c1eefd36ff9bf357e

test:
  secret_key_base: 08bc50de4f8aca7e5e887f695147945aedac1f9f6423ab9324e3dedf12f5f00b60a9b3abb7b28a661e5790f718bedaafc4a4fe959af04fa202030fc659a40db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
